"""Tests for plugins/flow/hooks/codex_agents.py, run as the hook runs it."""

import importlib.util
import json
import os
import re
import subprocess
import sys

import pytest

from conftest import REPO_ROOT

FLOW = REPO_ROOT / "plugins" / "flow"
HOOK = FLOW / "hooks" / "codex_agents.py"
RENDER = FLOW / "scripts" / "render_codex_agents.py"
NAMES = {"flow-code-reviewer", "flow-review-validator", "flow-tester"}
tomllib = pytest.importorskip("tomllib")  # Python 3.11+


@pytest.fixture
def home(tmp_path):
    return tmp_path / "codex-home"


def spawn(home, cwd, tool_input, tool="spawn_agent"):
    p = subprocess.run(
        [sys.executable, str(HOOK)],
        input=json.dumps({"tool_name": tool, "cwd": str(cwd),
                          "tool_input": tool_input}),
        capture_output=True, text=True, env={**os.environ, "CODEX_HOME": str(home)})
    return p.returncode, p.stderr


def agents(folder):
    return {f.stem: tomllib.loads(f.read_text(encoding="utf-8"))
            for f in folder.glob("*.toml")}


def test_first_spawn_installs_and_asks_for_restart(home, tmp_path):
    code, err = spawn(home, tmp_path, {"agent_type": "flow-tester", "message": "x"})
    assert code == 2 and "restart Codex" in err
    installed = agents(home / "agents")
    assert set(installed) == NAMES
    for name, agent in installed.items():
        assert agent["name"] == name and agent["description"]
        assert agent["developer_instructions"].startswith("You are running in Codex.")
        assert "sandbox_mode" not in agent  # Codex ignores it in role files


def test_body_survives_round_trip(home, tmp_path):
    spawn(home, tmp_path, {"agent_type": "flow-tester"})
    body = (REPO_ROOT / "plugins/flow/agents/code-reviewer.md").read_text(encoding="utf-8")
    body = body.split("\n---\n", 1)[1].strip()
    instructions = agents(home / "agents")["flow-code-reviewer"]["developer_instructions"]
    assert instructions.endswith(body)


def test_stale_agent_is_refreshed_and_spawn_allowed(home, tmp_path):
    spawn(home, tmp_path, {"agent_type": "flow-tester"})
    stale = home / "agents" / "flow-tester.toml"
    stale.write_text("# Generated by flow's scripts/codex_agents.py.\nname = \"old\"\n")
    assert spawn(home, tmp_path, {"agent_type": "flow-tester"}) == (0, "")
    assert agents(home / "agents")["flow-tester"]["name"] == "flow-tester"


def test_sync_removes_only_generated_orphans(home, tmp_path):
    spawn(home, tmp_path, {"agent_type": "flow-tester"})
    folder = home / "agents"
    (folder / "flow-old.toml").write_text("# Generated by flow's scripts/codex_agents.py.\n")
    (folder / "flow-mine.toml").write_text('name = "flow-mine"\n')
    assert spawn(home, tmp_path, {"agent_type": "flow-tester"})[0] == 0
    assert not (folder / "flow-old.toml").exists()
    assert (folder / "flow-mine.toml").exists()


def test_project_install_is_refreshed_in_place(home, tmp_path):
    project = tmp_path / "project"
    folder = project / ".codex" / "agents"
    folder.mkdir(parents=True)
    (folder / "flow-tester.toml").write_text("# Generated by flow's scripts/codex_agents.py.\n")
    assert spawn(home, project / "src", {"agent_type": "flow-tester"})[0] == 0
    assert set(agents(folder)) == NAMES
    assert not (home / "agents").exists()


@pytest.mark.parametrize("tool_input", [
    {"agent_type": "explorer", "message": "x"},
    {"message": "x"},
    {"subagent_type": "flow:tester", "prompt": "x"},  # Claude Code's Agent tool
])
def test_other_spawns_pass_through(home, tmp_path, tool_input):
    assert spawn(home, tmp_path, tool_input) == (0, "")
    assert not home.exists()


def test_unknown_flow_role_is_denied(home, tmp_path):
    spawn(home, tmp_path, {"agent_type": "flow-tester"})
    code, err = spawn(home, tmp_path, {"agent_type": "flow-nope"})
    assert code == 2 and "flow-tester" in err


def test_home_codex_folder_is_not_a_project_folder(home, tmp_path):
    # A leftover ~/.codex/agents from the old setup-codex isn't where Codex
    # reads roles when CODEX_HOME points elsewhere.
    user = tmp_path / "user"
    stale = user / ".codex" / "agents"
    stale.mkdir(parents=True)
    (stale / "flow-tester.toml").write_text("# Generated by flow's scripts/codex_agents.py.\n")
    p = subprocess.run(
        [sys.executable, str(HOOK)],
        input=json.dumps({"tool_name": "spawn_agent", "cwd": str(user / "repo"),
                          "tool_input": {"agent_type": "flow-tester"}}),
        capture_output=True, text=True,
        env={**os.environ, "CODEX_HOME": str(home), "HOME": str(user),
             "USERPROFILE": str(user)})
    assert p.returncode == 2
    assert set(agents(home / "agents")) == NAMES


def test_sync_leaves_no_temp_files(home, tmp_path):
    spawn(home, tmp_path, {"agent_type": "flow-tester"})
    assert sorted(f.name for f in (home / "agents").iterdir()) == sorted(
        f"{n}.toml" for n in NAMES)


def test_shipped_agents_match_their_sources():
    spec = importlib.util.spec_from_file_location("render", RENDER)
    render = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(render)
    wanted = dict(render.render(p) for p in sorted((FLOW / "agents").glob("*.md")))
    shipped = {p.name: p.read_text(encoding="utf-8")
               for p in (FLOW / "codex-agents").glob("*.toml")}
    assert shipped == wanted, (
        "codex-agents/ is stale: run python3 plugins/flow/scripts/render_codex_agents.py")


def test_installed_agents_are_the_shipped_copies(home, tmp_path):
    spawn(home, tmp_path, {"agent_type": "flow-tester"})
    for shipped in (FLOW / "codex-agents").glob("*.toml"):
        assert (home / "agents" / shipped.name).read_text(encoding="utf-8") == \
            shipped.read_text(encoding="utf-8")


def test_codex_settings_come_from_codex_keys():
    for source in (FLOW / "agents").glob("*.md"):
        text = source.read_text(encoding="utf-8")
        shipped = tomllib.loads((FLOW / "codex-agents" / f"flow-{source.stem}.toml")
                               .read_text(encoding="utf-8"))
        for src, key in (("codex-model", "model"),
                         ("codex-effort", "model_reasoning_effort")):
            value = re.search(rf"^{src}:\s*(\S+)$", text, re.M)
            assert shipped.get(key) == (value and value.group(1)), (source.name, key)
