#!/usr/bin/env python3
"""PreToolUse hook on Agent: keep flow's Codex custom agents current.

Codex can't load agents from a plugin, only from a `.codex/agents/` folder in
the project or `$CODEX_HOME/agents/` (default `~/.codex/agents/`). When Codex
spawns a flow-* role (Codex's spawn_agent tool, matched as Agent), this hook
converts flow's Claude Code agents (agents/*.md) into Codex role files and
syncs them:

- The role's file exists: rewrite any flow-*.toml that differs from the
  current plugin, delete generated ones that no agent matches, and allow
  the spawn. Codex reads a role file at spawn time, so the update applies.
- It doesn't: install all of them in $CODEX_HOME/agents/ and deny the spawn.
  Codex lists roles once per session, so they work after a restart.

Every other spawn passes through, including Claude Code's Agent tool, which
names flow's agents flow:<name> in subagent_type.

The conversion, per agents/<name>.md:
- frontmatter `name` becomes `name = "flow-<name>"`, the role name Codex
  sends as agent_type (guard.py matches it).
- frontmatter `description` is copied as is.
- `codex-model` and `codex-effort` become `model` and
  `model_reasoning_effort`. They are flow's own keys, set per agent
  separately from the Claude ones; Claude Code ignores them. Without them,
  a Codex agent runs on the parent session's model and effort.
- the Markdown body becomes `developer_instructions`, after a preamble that
  maps Claude Code tool names to Codex ones.
- `tools`, `model`, `effort`, and other frontmatter are dropped. Codex
  roles can't limit tools, and sandbox_mode is ignored in role files, so
  guard.py enforces the limits on both hosts.
"""
import json
import os
import re
import sys
from pathlib import Path

AGENTS = Path(__file__).resolve().parent.parent / "agents"
# Every generated file starts with this, including ones from earlier flow
# versions ("scripts/codex_agents.py", "scripts/render_codex_agents.py").
GENERATED = "# Generated by flow's "
PREAMBLE = (
    "You are running in Codex. These instructions were written for Claude "
    "Code: where they name a tool you don't have (Read, Grep, Glob, LSP, "
    "codegraph_explore), use the closest one you do have. Ignore mentions of "
    "hooks; flow's hooks enforce the same limits.\n\n"
)


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not m:
        sys.exit(f"{path}: no frontmatter")
    fields = dict(re.findall(r"^([\w-]+):[ \t]*(.*)$", m.group(1), re.M))
    for key in ("name", "description"):
        if not fields.get(key):
            sys.exit(f"{path}: frontmatter has no {key}")
    return fields, m.group(2).strip()


def toml_string(s):
    # A JSON string literal is a valid TOML basic string.
    return json.dumps(s, ensure_ascii=False)


def render(path):
    """(role, TOML text) for one agents/<name>.md."""
    fields, body = parse(path)
    name = fields["name"]
    settings = "".join(
        f"{key} = {toml_string(fields[src])}\n"
        for src, key in (("codex-model", "model"),
                         ("codex-effort", "model_reasoning_effort"))
        if fields.get(src))
    # Codex ignores sandbox_mode in role files, so none is set; guard.py
    # enforces the reviewer and tester limits instead.
    return f"flow-{name}", (
        f"{GENERATED}hooks/codex_agents.py from the flow plugin's agents/.\n"
        "# flow's hooks overwrite this file when flow updates; edits here are lost.\n"
        f"name = {toml_string('flow-' + name)}\n"
        f"description = {toml_string(fields['description'])}\n"
        f"{settings}"
        f"developer_instructions = {toml_string(PREAMBLE + body)}\n"
    )


def sync(folder, wanted):
    """Make folder's flow-*.toml match wanted ({role: toml text})."""
    folder.mkdir(parents=True, exist_ok=True)
    for role, text in wanted.items():
        out = folder / f"{role}.toml"
        if not out.is_file() or out.read_text(encoding="utf-8") != text:
            # Parallel spawns may sync at once, and Codex may be reading the
            # file: replace it whole, never truncate it in place.
            tmp = folder / f".{role}.{os.getpid()}.tmp"
            tmp.write_bytes(text.encode("utf-8"))
            os.replace(tmp, out)
    for old in folder.glob("flow-*.toml"):
        if old.stem not in wanted and old.read_text(
                encoding="utf-8", errors="replace").startswith(GENERATED):
            old.unlink(missing_ok=True)


def home_agents():
    return Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex") / "agents"


def installed_folder(role, cwd):
    """The agents folder that already holds role's file, or None."""
    cwd = Path(cwd).resolve()
    # ~/.codex is the default CODEX_HOME, not a project: Codex ignores it
    # when CODEX_HOME points elsewhere.
    projects = [d / ".codex" / "agents" for d in (cwd, *cwd.parents)
                if d != Path.home()]
    for folder in projects + [home_agents()]:
        if (folder / f"{role}.toml").is_file():
            return folder
    return None


def main():
    data = json.load(sys.stdin)
    role = (data.get("tool_input") or {}).get("agent_type") or ""
    if not role.startswith("flow-"):
        return
    wanted = dict(render(p) for p in sorted(AGENTS.glob("*.md")))
    if role not in wanted:
        print(f"flow has no agent {role}; use one of: {', '.join(wanted)}",
              file=sys.stderr)
        sys.exit(2)
    folder = installed_folder(role, data.get("cwd") or ".")
    if folder:
        sync(folder, wanted)
        return
    sync(home_agents(), wanted)
    print(f"flow installed its agents in {home_agents()}; restart "
          "Codex to use them. Until then, spawn the built-in explorer "
          "(reviewers) or worker (tester) with the matching agents/<name>.md "
          "body as its instructions.", file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
