#!/usr/bin/env python3
"""Generate Codex custom agents from flow's Claude agent files.

Codex can't load agents from a plugin, only from ~/.codex/agents/ (or
$CODEX_HOME/agents/). This writes one flow-<name>.toml there per
agents/<name>.md. An agent whose tools don't include Write or Edit gets
sandbox_mode = "read-only", which is how Codex enforces what guard.py
enforces on Claude Code.

Usage: codex_agents.py [--dest DIR]
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

AGENTS = Path(__file__).resolve().parent.parent / "agents"
PREAMBLE = (
    "You are running in Codex. These instructions were written for Claude "
    "Code: where they name a tool you don't have (Read, Grep, Glob, LSP, "
    "codegraph_explore), use the closest one you do have. Ignore mentions of "
    "hooks; your sandbox enforces the same limits.\n\n"
)


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not m:
        sys.exit(f"{path}: no frontmatter")
    fields = dict(re.findall(r"^([\w-]+):[ \t]*(.*)$", m.group(1), re.M))
    for key in ("name", "description"):
        if not fields.get(key):
            sys.exit(f"{path}: frontmatter has no {key}")
    tools = {t.strip() for t in fields.get("tools", "").split(",")}
    return fields["name"], fields["description"], tools, m.group(2).strip()


def toml_string(s):
    # A JSON string literal is a valid TOML basic string.
    return json.dumps(s, ensure_ascii=False)


def render(path):
    name, description, tools, body = parse(path)
    sandbox = "workspace-write" if tools & {"Write", "Edit"} else "read-only"
    return f"flow-{name}", (
        "# Generated by flow's scripts/codex_agents.py. Re-run it to update;\n"
        "# edits here are overwritten.\n"
        f"name = {toml_string('flow-' + name)}\n"
        f"description = {toml_string(description)}\n"
        f"sandbox_mode = {toml_string(sandbox)}\n"
        f"developer_instructions = {toml_string(PREAMBLE + body)}\n"
    )


def main(argv=None):
    codex_home = Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--dest", type=Path, default=codex_home / "agents",
                        help="target directory (default: %(default)s)")
    args = parser.parse_args(argv)
    sources = sorted(AGENTS.glob("*.md"))
    if not sources:
        sys.exit(f"no agent files in {AGENTS}")
    args.dest.mkdir(parents=True, exist_ok=True)
    for src in sources:
        name, toml = render(src)
        out = args.dest / f"{name}.toml"
        out.write_bytes(toml.encode("utf-8"))
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
