#!/usr/bin/env python3
"""Convert flow's Claude Code agents (agents/*.md) into Codex custom agents
in codex-agents/.

Codex can't load agents from a plugin, so hooks/codex_agents.py copies these
files into the user's Codex agents folder. agents/*.md is the only source:
run this after editing one and commit the result.
tests/test_flow_codex_agents.py fails while the two disagree.

The conversion, per agents/<name>.md:
- frontmatter `name` becomes `name = "flow-<name>"`, the role name Codex
  sends as agent_type (guard.py matches it).
- frontmatter `description` is copied as is.
- the Markdown body becomes `developer_instructions`, after a preamble that
  maps Claude Code tool names to Codex ones.
- `tools`, `model`, and other frontmatter are dropped: Codex roles can't
  limit tools, and sandbox_mode is ignored in role files, so guard.py
  enforces the limits on both hosts.

Usage: python3 plugins/flow/scripts/render_codex_agents.py
"""
import json
import re
import sys
from pathlib import Path

PLUGIN = Path(__file__).resolve().parent.parent
AGENTS = PLUGIN / "agents"
OUT = PLUGIN / "codex-agents"
# hooks/codex_agents.py deletes generated files no agent matches by this
# prefix. Earlier versions wrote "scripts/codex_agents.py" or
# "hooks/codex_agents.py" after it.
GENERATED = "# Generated by flow's "
PREAMBLE = (
    "You are running in Codex. These instructions were written for Claude "
    "Code: where they name a tool you don't have (Read, Grep, Glob, LSP, "
    "codegraph_explore), use the closest one you do have. Ignore mentions of "
    "hooks; flow's hooks enforce the same limits.\n\n"
)


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not m:
        sys.exit(f"{path}: no frontmatter")
    fields = dict(re.findall(r"^([\w-]+):[ \t]*(.*)$", m.group(1), re.M))
    for key in ("name", "description"):
        if not fields.get(key):
            sys.exit(f"{path}: frontmatter has no {key}")
    return fields["name"], fields["description"], m.group(2).strip()


def toml_string(s):
    # A JSON string literal is a valid TOML basic string.
    return json.dumps(s, ensure_ascii=False)


def render(path):
    """(file name, TOML text) for one agents/<name>.md."""
    name, description, body = parse(path)
    # Codex ignores sandbox_mode in role files, so none is set; guard.py
    # enforces the reviewer and tester limits instead.
    return f"flow-{name}.toml", (
        f"{GENERATED}scripts/render_codex_agents.py from the flow plugin's agents/.\n"
        "# flow's hooks overwrite this file when flow updates; edits here are lost.\n"
        f"name = {toml_string('flow-' + name)}\n"
        f"description = {toml_string(description)}\n"
        f"developer_instructions = {toml_string(PREAMBLE + body)}\n"
    )


def main():
    OUT.mkdir(exist_ok=True)
    wanted = dict(render(p) for p in sorted(AGENTS.glob("*.md")))
    for old in OUT.glob("*.toml"):
        if old.name not in wanted:
            old.unlink()
    for name, text in wanted.items():
        (OUT / name).write_bytes(text.encode("utf-8"))
        print(f"wrote {OUT / name}")


if __name__ == "__main__":
    main()
